; Performance tuning
memory_limit = 256M
realpath_cache_size = 8M
realpath_cache_ttl = 600
max_execution_time = 30
upload_max_filesize = 20M
post_max_size = 25M

; Disable unnecessary
expose_php = Off
